[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
install-cmd = "npm install --legacy-peer-deps"
node-version = "20"
