[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev --no-fund --no-audit --loglevel=error && npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
node-version = "18"
